ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

execute:
  freeze: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "A blog with nbdev"
  site-url: "https://hamelsmu.github.io/nbdev_blog/"
  description: "Create delightful software with Jupyter Notebooks"
  execute:
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  navbar:
    background: primary
    search: true
